# Debian provisioning
---
- hosts: all
  vars:
    home: "/home/{{ user }}"
  sudo: True
  tasks:
    - name: ensure basic packages
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - ethtool
        - git
        - vim-nox
        - zsh
        - screen
        - autoconf
        - automake
        - gcc
        - build-essential
        - libtool
        - libncurses-dev
        - tcpdump
        - hfsprogs
        - elfutils
        - libdw-dev
        - gettext
        - flex
        - bison
    - name: download dracut 040
      get_url:
        # tarball in kernel.org doesn't work
        url: http://www.mirrorservice.org/pub/linux/utils/boot/dracut/dracut-040.tar.gz
        dest: '{{home}}/dracut-040.tar.gz'
    - name: untar dracut
      shell: tar xzf {{home}}/dracut-040.tar.gz -C {{home}}/
    - name: install dracut
      shell: cd {{home}}/dracut-040 && ./configure && make && make install && cd -
    - name: download systemtap
      git: >-
        repo=https://github.com/RasPlex/systemtap.git
        dest='{{home}}/systemtap'
    - name: patch systemtap
      lineinfile: >-
        dest={{home}}/systemtap/configure
        state=present
        regexp='{{ item.regexp }}'
        line='echo ignore msgfmt missing'
      with_items:
      - regexp: 'missing gnu /usr/bin/msgfmt'

    - name: compile systemtap
      shell: cd {{home}}/systemtap && ./configure python='/usr/bin/python' pyexecdir='${exec_prefix}/lib/python2.7/dist-packages' --prefix=/home/vagrant/systemtap-3.2-14849 && make all && cd -
    - name: install systemtap
      shell: cd {{home}}/systemtap && make install

    - name:  edit dracut.conf
      lineinfile: >-
        dest=/etc/dracut.conf
        create=yes
        state=present
        line='add_drivers+="e1000e e1000 ixgbe"'
      #- name: touch .bashrc
      #file: path={{home}}/.bash_profile owner={{ user }} mode=0644 state=touch
    - name: set PATH for bash
      lineinfile: >-
        dest={{home}}/.bash_profile
        create=yes
        state=present
        line='export PATH=$PATH:/sbin:/usr/sbin:/usr/local/sbin'
    - name: make ~/deployed
      file: path={{home}}/deployed owner={{user}} mode=0777 state=directory
 #    - name:  edit grub
 #      blockinfile:
 #        dest: /etc/default/grub
 #        block: |
 #          GRUB_TERMINAL="serial"
 #          GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"
 #
    - name: create /etc/init/ttyS0.conf
      blockinfile:
        dest: /etc/init/ttyS0.conf
        create: yes
        state: present
        block: |
          start on stopped rc RUNLEVEL=[2345]
          stop on runlevel [!2345]
          respawn
          exec /sbin/getty -8 115200 ttyS0

    - name: grub cmd line for subsequent kernel install
      lineinfile:
        dest: /etc/default/grub
        create: no
        state: present
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash console=tty0 console=ttyS0,115200"'
